name: ((appli))
director_uuid: 8dd35958-abc4-46fc-9c96-f91c791bfeae

releases:
  - name: mongodb-service
    version: latest

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 1 #<-- important to limit max in flight
  serial: false

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: mongod
  release: mongodb-services
  azs: [z1]
  instances: 3 # 
  vm_type: small
  env:
    bosh:
      swap_size: 0
  stemcell: trusty
  networks:
  - name: mongodb-net
  persistent_disk_type: small
  env:
    persistent_disk_fs: xfs
  jobs:
  - name: mongod
    release: mongodb-services
    properties: 
      node_role: rs
      require_ssl: 0
      replication:
        enable: 1
        key: ((mongo_keyfile_content))
      root_password: ((mongo_root_password))
      admin_password: ((mongo_admin_password))
      server_certificate: 
        ca: ((mongo_ca.ca))
        private_key: ((mongo_ca.private_key))
        certificate: ((mongo_ca.certificate))

- name: mongodb-broker
  instances: 1
  vm_type: default
  stemcell: trusty
#  azs: [z1]
  networks: [{name: mongodb-net}]
  persistent_disk_type: test_disk
  jobs:
  - name: broker-smoke-tests
    release: mongodb-services
    properties:
      cf:
        api:
          url: ((cf.api.url))
        admin:
          username: admin
          password: ((cf.admin.password))
        skip:
          ssl:
            validation: true
        org: service-sandbox
        space: mongodb-smoke-tests
        mongodb:
          appdomain: ((cf.mongodb.appdomain))
          servicename: mongodb
          serviceplan: default
          serviceinstancename: mongodb-instance
  - name: broker
    release: mongodb-services
    consumes:
      server: {from: deployment-server}
    properties:
      broker:
        user: mongodb-broker
        password: ((broker.password))
      mongodb_node:
        root_username: MongoRoot
        root_password: ((!mongo_root_password))

variables:
- name: mongo_admin_password
  type: password
- name: mongo_root_password
  type: password
- name: mongo_certificate
  type: certificate
  options:
    is_ca: true
    common_name: mongo-cert
