---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
  - name: deployed-version

outputs:
  - name: output  

run:
  path: mongodb-bosh-release/ci/scripts/bump-version.sh

