---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-bosh-release

outputs:
  - name: bosh-director-config

run:
  path: mongodb-bosh-release/ci/common/scripts/create-bosh-config.sh

params:
  ALIAS: ""
  CA_CERT: ""
  IP: ""
  PASSWORD: ""
  USER: ""  