---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/credhub-cli
    tag: latest

inputs:
  - name: mongodb-bosh-release

outputs:
  - name: broker-password

run:
  path: mongodb-bosh-release/ci/scripts/get-broker-password.sh

params:
  IP: ""
  PASSWORD: ""
  PORT: ""
  USER: ""
  VAR: ""
  BOSH_ALIAS: ""
  DEPLOYMENT_NAME: ""