---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/credhub-cli
    tag: latest

inputs:
  - name: mongodb-bosh-release

run:
  path: mongodb-bosh-release/ci/scripts/modify-mongo-password.sh

params:
  UAA_CA: ""
  USER: ""
  BOSH_ALIAS: ""
  CREDHUB_CA: ""
  DEPLOYMENT_NAME: ""
  IP: ""
  PASSWORD: ""
  PORT: ""  