---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: bosh-director-config
  - name: mongodb-bosh-release

run:
  path: mongodb-bosh-release/ci/scripts/run-acceptance-tests.sh

params:
  ALIAS: ""
  DEPLOYMENT_NAME: ""