---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-bosh-release
  - name: bosh-director-config

run:
  path: mongodb-bosh-release/ci/scripts/run-smoke-tests.sh

params:
  ALIAS : ""
  DEPLOYMENT_NAME: ""