---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
  - name: mongodb-bosh-release

run:
  path: mongodb-bosh-release/ci/scripts/udate-keyval-resource.sh

params:
  VALUE: ""