---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-version
  - name: mongodb-new-version
  - name: bosh-director-config
  - name: mongodb-bosh-release-patched  

run:
  path: mongodb-bosh-release-patched/ci/scripts/deployment/create-release.sh

params:
  BOSH_RELEASE: ""
  DEPLOYMENT_NAME: ""
  INSTANCE_GROUP: ""
  NETWORK: ""
  STEMCELL_TYPE: ""
  UUID: ""
  ALIAS: ""
  CURRENT: ""