---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-bosh-release
  - name: bosh-director-config
  - name: deployment-specs 

outputs:
  - name: output

run:
  path: mongodb-bosh-release/ci/scripts/data-insertion/get-deployment-ips.sh

params:
  IP: ""
  PASSWORD: ""
  USER: ""
  ALIAS: ""
  CA_CERT: ""
  DEPLOYMENT_NAME: ""  