---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/mongo-cli
    tag: latest

inputs:
  - name: bosh-director-config
  - name: mongodb-bosh-release
  - name: deployment-specs
  
outputs:
  - name: datas

run:
  path: mongodb-bosh-release/ci/scripts/data-insertion/insert-collection.sh