---
resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

  - name: mongo-src
    type: docker-image
    source:
      repository: jraverdyorange/concourse-mongodb-resource        

resources:

  - name: mongodb-bosh-release
    type: git
    source:
      uri:    ((repositories.mongodb.uri))
      branch: ((repositories.mongodb.branch))

  - name: mongodb-version
    type: semver
    source: &semver-source
      initial_version:  1.0.0
      driver:           git
      uri:              https://github.com/orange-cloudfoundry/mongodb-boshrelease.git
      branch:           master
      file:             mongodb_version
      username:         ((repositories.mongodb.username))
      password:         ((repositories.mongodb.password))
      git_user:         "((repositories.mongodb.git_user)) <((repositories.mongodb.email))>"
    
  - name: mongodb-new-version
    type: mongo-src
    source:
      branch: "3.6"

  - &deployment-lock
    name: deployment-lock
    type: pool
    source:
      uri: ((repositories.locks-pool.uri))
      branch: ((repositories.locks-pool.branch))
      pool: concourse-deployment-lock
      username: ((repositories.locks-pool.username))
      password: ((repositories.locks-pool.password))
  

jobs:

# clone current "main" blobstore to dev one
- name: clone-blobstore
  serial: true
  plan:
    - get: mongodb-bosh-release

    - get: mongodb-new-version
      trigger: true    

    - &create-bosh-config
      task: create-bosh-config
      file: mongodb-bosh-release/ci/tasks/create-bosh-config.yml
      params:
        CA_CERT:  ((bosh-server.ca))
        IP:       ((bosh-server.ip))
        ALIAS:    ((bosh-server.alias)) 
        USER:     ((bosh-server.user))
        PASSWORD: ((bosh-server.password))

    - task: blobstore-cleanup
      file: mongodb-bosh-release/ci/tasks/clone-blobstore/blobstore-cleanup.yml
      params:
        ACCESS_KEY_ID:      ((blobstores.release.access_key_id))
        SECRET_ACCESS_KEY:  ((blobstores.release.secret_access_key))
        ENDPOINT_URL:       ((blobstores.release.endpoint-url))
        BUCKET:             ((blobstores.release.bucket))
        SKIP_SSL:           ((blobstores.release.skip-ssl-validation))
        SSL_CERT:           ((blobstores.release.certificate))


    - task: get-release-blobs
      file: mongodb-bosh-release/ci/tasks/clone-blobstore/get-release-blobs.yml
      params:
        ALIAS:              ((bosh-server.alias))
        ACCESS_KEY_ID:      ((blobstores.release.access_key_id))
        SECRET_ACCESS_KEY:  ((blobstores.release.secret_access_key))
        ENDPOINT_URL:       ((blobstores.release.endpoint-url))
        BUCKET:             ((blobstores.release.bucket))     
        SIGNATURE_VERSION:  ((blobstores.release.signature-version))
        GOLANG_VERSION:     ((deployment.golang-version))

    - task: blobs-rename
      file: mongodb-bosh-release/ci/tasks/clone-blobstore/blobs-rename.yml
      params:
        ACCESS_KEY_ID:      ((blobstores.release.access_key_id))
        SECRET_ACCESS_KEY:  ((blobstores.release.secret_access_key))
        ENDPOINT_URL:       ((blobstores.release.endpoint-url))
        BUCKET:             ((blobstores.release.bucket))
        SIGNATURE_VERSION:  ((blobstores.release.signature-version))  

- name: prepare-blobstore
  serial: true
  plan:

    - get: mongodb-bosh-release

    - get: mongodb-new-version
      passed: [clone-blobstore]
      trigger: true          

    - aggregate:

      - get: mongodb-version

      - *create-bosh-config
        
    - &get-config-files
      task: get-config-files
      file: mongodb-bosh-release/ci/tasks/get-config-files.yml
      params: &get-config-files-params
        CURRENT: true # fetch current main release config
        CONFIG_PATH:        ((blobstores.release.config_path))
        ACCESS_KEY_ID:      ((blobstores.release.access_key_id))
        SECRET_ACCESS_KEY:  ((blobstores.release.secret_access_key))
        ENDPOINT_URL:       ((blobstores.release.endpoint-url))
        BUCKET:             ((blobstores.release.bucket))
        SIGNATURE_VERSION:  ((blobstores.release.signature-version))
        SKIP_SSL:           ((blobstores.release.skip-ssl-validation))
        SSL_CERT:           ((blobstores.release.certificate))
        GOLANG_VERSION:     ((deployment.golang-version))

    - &upload-new-blobs
      task: upload-new-blobs
      file: mongodb-bosh-release/ci/tasks/prepare-blobstore/upload-new-blobs.yml
      params:
        ACCESS_KEY_ID:            ((blobstores.release.access_key_id))
        SECRET_ACCESS_KEY:        ((blobstores.release.secret_access_key))
        ENDPOINT_URL:             ((blobstores.release.endpoint-url))
        BUCKET:                   ((blobstores.release.bucket))
        SIGNATURE_VERSION:        ((blobstores.release.signature-version))
        SKIP_SSL:                 ((blobstores.release.skip-ssl-validation))
        SSL_CERT:                 ((blobstores.release.certificate))

    - &upload-config-files
      task: upload-config-files
      file: mongodb-bosh-release/ci/tasks/prepare-blobstore/upload-config-files.yml
      params: &upload-config-files-params
        ACCESS_KEY_ID:      ((blobstores.release.access_key_id))
        SECRET_ACCESS_KEY:  ((blobstores.release.secret_access_key))
        ENDPOINT_URL:       ((blobstores.release.endpoint-url))
        BUCKET:             ((blobstores.release.bucket))
        SKIP_SSL:           ((blobstores.release.skip-ssl-validation))
        SSL_CERT:           ((blobstores.release.certificate))
        CONFIG_PATH:        ((blobstores.release.config_path))

- &deploy-current-version
  name: deploy-current-version
  serial: true
  plan:
    - &init-current-version
      do:
        - get: mongodb-bosh-release

        - aggregate: 
          - get: mongodb-version
            trigger: true

          - *create-bosh-config

    - &deployment-lock
      put: deployment-lock
      params: {claim: deployment-lock}

    - &get-config-files
      task: get-config-files
      file: mongodb-bosh-release/ci/tasks/get-config-files.yml
      params:
        ACCESS_KEY_ID:      ((blobstores.release.access_key_id))
        SECRET_ACCESS_KEY:  ((blobstores.release.secret_access_key))
        ENDPOINT_URL:       ((blobstores.release.endpoint-url))
        BUCKET:             ((blobstores.release.bucket))
        SIGNATURE_VERSION:  ((blobstores.release.signature-version))
        SKIP_SSL:           ((blobstores.release.skip-ssl-validation))
        SSL_CERT:           ((blobstores.release.certificate))
        GOLANG_VERSION:     ((deployment.golang-version))
        CURRENT:            true
      on_failure: &deployment-unlock
        put: deployment-lock
        params: {release: deployment-lock}
      on_abort:
        *deployment-unlock    
          
        
    - &deploy-replicaset
      task: deploy-replicaset
      file: mongodb-bosh-release/ci/tasks/deployment/deployment.yml
      attempts: 3
      params: &deploy-params
        CA_CERT:              ((bosh-server.ca))
        IP:                   ((bosh-server.ip))
        ALIAS:                ((bosh-server.alias))
        USER:                 ((bosh-server.user))
        PASSWORD:             ((bosh-server.password))
        RELEASE_NAME:         ((deployment.name))
        DEPLOYMENT_NAME:      ((deployment.name))
        DEPLOYMENT_NETWORK:   ((deployment.network))
        SHIELD_URL:           ((deployment.shield.core))
        SHIELD_TOKEN:         ((deployment.shield.token))
        SHIELD_TENANT:        ((deployment.shield.tenant))
        SHIELD_STORAGE:       ((deployment.shield.storage))
        MONGO_PORT:           ((deployment.mongodb.port))
        PERSISTENT_DISK_TYPE: ((deployment.mongodb.persistent-disk-type))
        VM_TYPE:              ((deployment.mongodb.vm-type))
        ROOT_USERNAME:        ((deployment.mongodb.root-username))
        ENGINE:               "wiredtiger"
        # for ssl deployment
        REQUIRE_SSL:          ((deployment.mongodb.require_ssl))
        CA_NAME:              ((deployment.mongodb.ca_name))
      on_failure:
        *deployment-unlock
      on_abort:
        *deployment-unlock            

    - <<: *deployment-unlock   