---
bosh-server:
  ip:                   ********
  alias:                ********
  user:                 concourse
  password:             concourse
  uuid:                 ********
  ca:                   |
                        -----BEGIN CERTIFICATE-----                                     
                        ***********
                        -----END CERTIFICATE-----
  is_bosh_lite:         true
  jumpbox_private_key:  |
                        -----BEGIN RSA PRIVATE KEY-----
                        ************
                        -----END RSA PRIVATE KEY-----

uaa:
  ca:           |
                -----BEGIN CERTIFICATE-----
                *****************
                -----END CERTIFICATE-----


credhub:
  ip:           ********
  port:         8844
  username:     ************
  password:     ***********
  ca:           |
                -----BEGIN CERTIFICATE-----
                **********
                -----END CERTIFICATE-----

cf:
  nats_host:      ***.***.***.***
  nats_password:  ************
  system_domain:  ************
  admin_password: ************
  org:            ***********
  space:          ************
  skip_ssl_validation: true

shield:
  core:             https://**************
  ca:               |
                    -----BEGIN CERTIFICATE-----
                    **************
                    -----END CERTIFICATE-----
  token:            ************
  tenant:           **************
  storage:          ************

repositories:
  mongodb:
    uri:        https://github.com/orange-cloudfoundry/mongodb-boshrelease.git
    branch:     dev-v8
    username:   ***********
    password:   "***********"
    git_user:   "************"
    email:      ***@**********

  locks-pool:
    uri:        https://github.com/**************
    branch:     master
    username:   ***********
    password:   "***********"
    git_user:   "***********"
    email:      ****************

blobstore:
  use_release_config:   false    
  access_key_id:        ************
  secret_access_key:    ***************
  endpoint-url:         ***************
  bucket:               ****************
  signature-version:    4
  skip-ssl-validation:  false
  certificate:          |
                        -----BEGIN CERTIFICATE-----
                        *****************
                        -----END CERTIFICATE-----
  http-bucket:          *********
  config_path:          *************

deployment:
  golang-version:       1.9
  name:                 ************
  network:              default

  mongodb:
    persistent-disk-type: 512MB
    vm-type:              small
    nb_instances:         3      
    port:                 27017
    root-username:        root
    database-name:        **************
    collection-name:      **************
    require_ssl:          false # Not completly implemented yet
    ca_name:              /internalCA
    ca_cert:              |
                          -----BEGIN CERTIFICATE-----
                         **********************
                          -----END CERTIFICATE-----


  broker:
    vm_type: small
    persistent_disk_type: 512MB
    catalog_yml: |
                services:
                - id: mongodb-service-broker-ci
                  name: mongodb
                  description: MongoDB 3.6.4 ci tests
                  bindable: true
                  plans:
                    - id: mongo-plan
                      name: default
                      description: A MongoDB database on demand on shared cluster.
                      free: false
                      metadata:
                        bullets:
                        - 100 MB Storage (not enforced)
                        - 40 concurrent connections (not enforced)
                        costs:
                          amount:
                            eur: 10.0
                          unit: MONTHLY
                        displayName: Shared MongoDB server
                  tags:
                    - mongodb
                    - orange
                    - document
                  metadata:
                    displayName: MongoDB 3.6.4 single Replicaset
                    imageUrl: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAABIFBMVEX///+UeV1ONilCmDRFoDZQq0FIpzpAlDNDmjRTrEONcFBLqDxDnDVDpDaRdVhWrkdLMiT39fNdsUxILh+zoY9EKRhCJRI+HQBAIg5bRjo+HwY+HgBDJxU8GgDw7erd1c6poZ7Guaze2djl39msmIXIv7acko3y7+zGwr9ltVPm5OO/ubbXzsW3sK3Py8llU0mehm2JfXd0ZFw6FQCbgmi+r6CmkHqCdW6jmpavz6u7uZ0unxvc6No6ois2lSViTkR5amOTiYMxAABmp11jsFkrjxU0CgDD3MB0rmzj7OK1zbGPwYifyZlZok4iAAB1s23M2siCqWm/vqOsqIifqX+TqXjV07zt6tqFZEBIkznN3spamUl1t2yGqWxxr2iFvX4MS4MNAAATh0lEQVR4nO1cDXvaOLZ2nJAGEhw7jsE4mBAIgRI+AjQJaUoCs+329nZmZ6ed293p7dz+/39xZckfknxkC+rZ7HT9tn2aCPlIr87ROdKRjKLkyJEjR44cOXLkyJEjR44cOXLkyJEjR44cOXLkyJEjR44cOXLkyJEjR44cOXLkyJEjR44cOXLkSEEr/Kkx6rUM/tPeqKWkoT/q9Vr9pBq9hv9D93I+b/b4Vnhpo0RhWE5LphZCq1n7oUseadZc23ZmS4rQaOKc2PaJe5tAst+cVqsOetK1l5dgDWO0sv7axD/2prOKZVn2bNKFpTWGUxc16VSr02YjLOWoGJe3pouatKvuuJnEsj+cqFVLN70B7a7suq56MN2LQO7YNVW/bCWQ0Zu6FnnOq2brTb7Ho/m0bptqfYh+aY2rQV3LGgHSRstq3TRNXEmvV6fDPuqb0b/4ga7cX3kCfeiWO2kAklBjk7Hq1Iks9GuzbqkhHEynsXT0qKyyBKU8OrpuVU8c1yHP6/YjNaa9aa1ikwGoIPVOqpRAfRaj2JiemHq1NpmM3TqpU7d1T6blRHWNiWOqJmrwpFrxVVIZQn2rBOpR9ZrSeLR1s16pB0VV9MgQVdCD8USwL+JC5jNdNXXPTozWXPc5Ur35W/i0ao/6NVRB1yOSDmdfPa/rYzIfmvWwnvdDNbTpFlKF7ky8Wv3LsU1quUDflP68FqqoaVqOuhr2Lleqr8l669bRLedxspo8nvi8T2IGf2sja1uGTuOiSnrkhpN2+FgNBs1cmbppV8bTsR60ay5Zgi56dhz2z6T0bU/CSsgMdDMcw55O5DsQRW+a1f05UR0Hz6yqvlGaVsWfw/1phXRowj1/i8rNKddHPOiRp+xPZgEffXY7Mki7RKDq0mPWcFm1tvyeqG51FjqBkVepSj1m1AhFF/Zxyop8bFIfz/3Wbcq1XJAyh3XxTcd7lCnzKVr0WDTG/mx5jPzx3Cb15lS9qckN4gR3zjaUiFB/5pUws85QifgqHH/6eJwqTCgYh46BbR2J7sWeZfro9YpYuUtLbGE6aLbHeh/ZpK+yCt1CyyHzl+6byQsKqqkW7OwbJ7G2lZ4dE6z0cZnFGDtm7XJz0/CN4jbWBavJNEysohqVrCyV9z01b6zrlMZ6DjCo/mipFVCJEEPlROUEK75idXrOYYPhH0WmS5Q4o5ojDFmjUJa4W9SMevRasBuxOvSw4l44/OKjQaYGHDIaVaCbWA475MqFxVfEJTHnEyiH5gMyJCNB9Rb/zjK8MFmV9TEVM6YrMlqMzwthOABDrHWO4RB7XYsqqQHj4GGKp7FJzQqQ4WWFndkGmXSMlc4t1piaddBsfFmqKc1wBTAkQipRQbcC2DLuhsX7EN+dsQz92c4zZGY/ZkgVYV3RkoO+nKicyacwxPbHzWfSoXpUACrGw8jhPSfIcMQxVMy4O8LGVI0MV405Ax/YnrjhSWI4BxiOeIa9ioBh14/6VNAHGTocQ+xpWAV5DoEusXnrCLAEglkSQ2xnnJUSHVJWeimyUsWBGXJVWzxDsvioUo4SOy2HGhhXxHCVAUOiQ8rTEIax2KT45ob3K2sx9K2b6r/nWBg+Vd7+A8ytP4AhUWo8WgSzhZ6HUICNMfQnUyUMf97iQXfp8EGWevFo4Xs3cB52N2bYijkUluGYr5rKcDTDBOwJYdBFjE2Lie7EOGIRP2AI+lJwTSPFsEEG1I0PKAm/sXiYylCZEx9lWqvL0eUE7Q8rj2yfSagF5j6xUitWLmI4F3oaWoYq8tCxMJLAkHWww5m/qq3YFVO3XH6S4zDGrnkJsKeBwojvBOQZ6lTJrQlPRBItZlSeSZoh2onizbFumnVHncfMgxgSsMTG0aLe5IuFDC9EVqpTDjJYKll8c9gnMuPpM2QFClYM/bFuWtPb1RDK7Rlkwx5fYmMnZYM5t77sqq0XY2j4m13elPAsrtLG689hVqCAYatmTgVpRiXcVapcMd4/cCkRpp3NGJINXdyDeWsTk4nKCQw50zVWMx1Whf8QSWzUuVHF24IZ/Fzc+BR4b4Ftkq3oe1P9kZXo9ZzdyJIFngTDSy9bZycl2JcmFDA8p1eBU1HB3GULp8C+iOye2IpNP33A+DZPhe4QeJZNEACKNXw3M4bzuxgNEjN1kx7CZoW3GgpkQVdhFUyc5JIpIzOAS3AuiZ1aVJ+mqKjKDSfxupwzJ0GabsWP+GgdM15dNIe9UQugGmTzTqJAOkSma9YEeah5YGijsILRIh1SrUl0RtO/8FPQ6pDhOLb8+DUnxT0vtceGse5oFaQsV6FAoz8MUozjYVDquy6sIsuq27ZzUq9NV5fsqDb9WidL4sz6E2RJlTFEsDVVnSCRr9vmIx744aPphClcRydZ1FXNDiuiOEVb0a1LempVasvbqWrrap1ZA3RR8A5PGEzb0rH9Tk2nrkYSgynUDBKkEXTdrDhLhuNlsCxw1OntsobEmzM4zdZ0dAzT/w8b8tTSaTi4QyqpYvo1Z7TxXOp+Xp18bOusm2u5bI+JF6Sz2SqVB5zEKWIuLpv3mwZJeNymxY0A1bcTtTYeT6fL6XQ8rvlJ3Fs0trXH8Xj8OH6s1fywNkYlU1TRr8n5peH0xLZMBMu2p3ws7v/gVE+cSqVer1e8A7MfcPxT3WqVKvTP3TxZpgly5CJBa2I5da9Nq1KtzWWOEL8R3VFzNbldgaeerVa/YeByw+j2+8TL91v9fpcqpJ5DHg0Ztm1XEINI0/Fdb2t4MbmdXFz+C+hli2Zdr0wuR6Pe5XA+GeuhT6hCW78/IYypbY3pU5fWquI7dkE8/5OhpZt1fmfUHZPoHN8x/QkxnOnQ6hln4AXL6k3wKjNJ68IL5Q7kq+xsdfglM0lrojeD81pkXQ3l9DaDsficlag14S1yLPD0yDNTJzNfeld8nZWo9TDCx61N6CO0W4nteTfGq+Lz+6dRIt5/glZq6PEt78Z4dfj8efkwI2HrgWwXHeCTno3Wnxm18rb4/Pnz3cWPGYlbC128OTSBTUJNV92MZuFd4bnHcOf+SSIGyfbaMXO8tVS3mU0Td/sewef7O+XFu2wkrgV/n+XcMiGxO62rscTwhrjbP/IZ7pTLT0Fx5R9VWxdhmql1UTF1Fwwh6+Nu9yhkiCgm3v78g+DfvFIttHmfrFbexUJLr6vpd1ul8HlxdEQo7pc9ivtPQXHiBjtC78Ig2h7qVmZh4t3+EcNwp/wkgd+7zhrdSDQddS5Of6+Jo8OQYQEz3Fk8zdpmtFJdfN34xK2tMtz1fikQhkcRw53F++zkrwWj3xqNWv1Mp8nd7mHEsLjjY3GXZRtPineI4GFopoWdkOLT7RUzxutCyPCI0iECVLs7GAxOEdrtfrtBgH5qt72y00GHxqAtb2sGqo5ktgOZWC4WTCQTtNubuJ67clHAcPEVqH5TSoAWK9m6uR4knLSEOE4SyzRxdSwlMIKxKGKGh4AOge3waWlrPWiI9dbxaUov+vJiPYFXZ2s4oq/7xSKtRJohYKdX2poMSa9KpeN2Ui+O1xSL5Mna66tFIYFhLGS0/6ltRNEjeZOgSG1tsVrpTI7hF0+FtJmyOrzn1uCNzvU5GkCgPxo9B8EOI45CPQ7Ojq9KgNxQKiCwdCNjqp8XhUKRViLHsPwz9FS7c863qN102o2uYRjdbqM96BzfeOMQ53ic1Cmj3blh56N23PEc92DgDywnbkvCUl/vFwqsmR4yDCFnQ3pzxvRFO4/VaAyOt2Ikta3E6YgGj35CO2YFnnPytK1ULaJZGOmQUGR1uLMjTKAOaIoluOPt4xjHtOlDiy0NuA+716w87SaN4dfdQoEzU56hOPdGu9WSyF6MM96eS8eCqj5ohnHf1GCdeamTLKy78IyUNVPOSnd2/k/0dIfui9hcjGsu1pXiFk3jJqIAMFSUc1aLyXb646JQ4M00xpB3pyHaJcmG2lusGpO1SIVG2PZvaGkpSjza3S/wZspb6U4ZWrt5aMjpEPeaVWMixVSGCiPrRVK7r+73CcNCEsMdUdKmK6tDhbXolJFPZ8isHBPH9sfy/n7MTGNWKtworsOQX88K+i7HULmiJSUtecu7+/sxM+UYHqA/goSGsQ7D2JJdiqFgE9GhZqKWEH3eISONmynD8ODA+yvwNesxZOMnF8xpXFMMBTctGOtJmNN3i5gOD715eOCrDpHzCB4cPMBmuiZDhV0FCe1UgiHta4DVVIjX2Ep5My16WsPkIorbmTBk3bx29Q0MqZiYwNAo7+4CZnqIDZOoMQBspjRD8bSiH2CXI/ySzIfEPKTrJDB8tdjdBcy0eBAHbKZMh2UYsjFDpEQZhpSetWthc3c+Q85MIYbwym1tHSrKC0aJsJ+XYXhG1RGYAsJXhmEhieEBmHXbgCETMgT2taYOhXWwowHMFGb4BkqdbsCQTfPAyxEZhpSnSVi1LQKGLEWQITgRN2HIBEUNXLvJMKRGSbz+e3fPMiwkMvyvjBgyq2Z4/yrBkI744qY+E4YxMwUY7u0d/JQVQyZtCEbRtVZtCX4GudIyaKYUwz3Ejfw7eMiKIbsvgLwpzVCwjghdctKCBu1+y6CZFn21edS8/8gPb4AsxUYMFWYiQqvmdIbhZNYSm33vM+TNtBhR2wsI7u1BznT9iO+BXrqBKkhlGLabkk38GTGEzLS4FwNS6QOQj9pMh2f0uECuPo2hEeREtBfJi+EvZZ5hIcYw0ubD26wYpm7QUxiGSZ+0nB0K+GXQTIsUvQgP/50Vwy7DEHCWiQzbQcantJV2nKUclWNKxBSLLLWAIRDyN2OoMKsaYJNI7xturs86nQFBBx9t+B++SMmTChgWCEMIGTJMS7LQEVPzEJ32hJ9oHYkTi4jhLqdDHtvbe9sZMqSdKRSwpY4StdLVWRpJwjBupkWWGv6TqQ4ZHQHGJntYqpXOk095Xi9gMy1iah457+925p4mM4b4QDLpRP/nBWymxe2IFzUPM4sWazFMO3VNPAh+vxCYaZweovzw98wYXsvPQ+RQDMM/dT0deIekMZalK2HY/xFiWGAZbocAV21/OMNYPGx0buIHwSJLfXtfhs10myNHGAJiMrDSlHgIrWka17GDYIFTfeUzjJnpNoTMdk/fzBC1y51kiXYYxgJiWCgWIIJ7me2A2RNO6OhYYn/InYGIEvuvy6CZggwfoDPEDCK+BnwuwVBpsGeughOC9wuQIswwq0yUwuRMwaSwDEOlK3Nh4S08EUGGb6DrCt++8gbNS4ohc8QuUqIB6rAAMXz2AG5Fv3n3BKYT5RhyKS14Jr6GKUI6/Av0/LfvgMGhl2TIHvNAE5pk2wBvKjsNs8hiQBXO5RgyKwdB3rF7D+lw/xkwDbM5XeMJwLlAWYbMTBSc8oBmugMw/A18fDOGKWs2eYZs+hze84PeFGAoccotzZC+DAwTkGZILx1E9xXK6Tp8hgAb6WYMz9KMVJ7hmQTDO8BMQ4bPAmxDxzKbMqSyNIK5I81wIMEQWpvuPOMBhnuOodRNBYV1D4JTbnmGaZHVA71J9HV4wBPchlbdmzKkD28Fx0bSDJnIKjyDiptpjOEbIIGxKUM6TIsObzfSofgW2d09b6Z7PEORCjdhSKtQlLOmGSa+OkLf/SqJqx3yCSmeoWgWrnlzD4MaE/H95RtZhvSVE9H1IyXa6ocUtzmGAkeqsPdL5RjS6xnhA9IMqYpCR+PhPZc35Rg+iF96XuMGLQE1cRJOp6UZblHNJ+a/OR1yBBNeQkxfnrCg3EzShcIrSYZU4Ek87A7t1KdY+E3OzbBNpAwi3/XElwioHEDCPVupm7YBiD8lBHeP/lfSRjmGKW0o9CRMPrylGSacEdJeK+2sVPmyCHW4+xPN8A1wWhFBLuIGiIY85U2XLTmpdGo8rW1FKYYUd/9CMXxIftmZWTWlDeONpAaZyxoJUqnhlbAf5V14a2H3l18ihmDuIgJzlzJ5InbpOZhMkFnPC2MKlWtLe22GwPM2WIXl338PCcL73ghMGiHRnQ2iA5XU+wUNhqFgy9CN8qWyryF+9imWf/81DIhpAYC5LJrQ9X70yp2WPl/ZC+9wvDiNji7kNOjhLbnmtvj1o89vO+37TdiMpTe/wN63qVfqkk80CZjL4ODJUv88GjEt9UZGBEKx/PGl72rSCJ5uxVDauj5lpqNxev0i4qdJjHc3dgJcumYciTGgztdKV2u9vI4vKx5+/Pg/D8iL/pRooka78wJ8+VorlbSb4+szD9xrpCnvj3rsTs+u4u+dejJfnBOZ7IukWuJqFMI75FB/+vjx5W/P3oiX24pnR8ALsFSPQjDdPE420Gs8OiKxgMj0EQNgvL7/5ePLly+3E78LqwNqLwlaSbtOMafGmkI1+bfVWXz9FTH8kBxB1+yKJvF9A1zkSaf3Yp1vHGCBjPTDh8QaXenR9q4zaTfXEisOPvIkDljpSk6kAB8Qw+QRb/9T8H0VEcJvxOi0JYfagIR6A8TLPD87/cavHTpFRpoSs4wugvfVI+EXj5CLdf71us7A+5KSxpr9MPxbJVgylupJ7HTOAiDx7fW+8EOANjLSTAT928J4+eHTU3zN178QHz58euou/MH4D2D46Xtn+Ok/geF37mk+ffrHd87w9NM/Mvuuwn9TNL53HebIkSNHjhw5cuTIkSNHjhw5cuTIkSNHju8H/w+Aj2085/ndoQAAAABJRU5ErkJggg==
                    longDescription: MongoDB is a free and open-source cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with schemas. MongoDB is developed by MongoDB Inc. and is free and open-source, published under a combination of the GNU Affero General Public License and the Apache License.
                    providerDisplayName: Orange
                    documentationUrl: https://docs.mongodb.com/
                    supportUrl: https://contact-us
                      

communication:

  mail:
    host:   **************
    port:   "25"
    to:     [ "***@*****", "****@*******" ]

  http:
    port: 666
    ip: **********
